# Generated by Django 3.1.2 on 2026-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220617_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_mode',
            field=models.IntegerField(choices=[(1, 'Coach and teams'), (2, 'Individual'), (3, 'Individual school'), (4, 'Individual for Huawei')], default=1, verbose_name='registration mode'),
        ),
    ]
