# Generated by Django 3.1.2 on 2026-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proglangs', '0005_auto_20200627_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('kt', 'Kotlin'), ('pas', 'Pascal'), ('dpr', 'Delphi'), ('py', 'Python'), ('cs', 'C#'), ('sh', 'Shell'), ('zip', 'ZIP'), ('asm', 'Asm')], default='', max_length=8, verbose_name='language'),
        ),
    ]
