# Generated by Django 3.1.2 on 2026-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0015_solution_is_plagiarism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgementlog',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Solution compilation log'), (1, 'Checker compilation log')], default=0),
        ),
    ]
