# Generated by Django 3.1.2 on 2026-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_auto_20200312_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryaccess',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Read'), (2, 'Modify'), (3, 'Write')]),
        ),
    ]
