# Generated by Django 3.1.2 on 2024-05-02 12:20

import common.ir18n.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_auto_20210706_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemrelatedsourcefile',
            name='file_type',
            field=models.IntegerField(choices=[(215, "Author's solution"), (216, 'Checker'), (217, 'Contestant solution'), (218, 'Generator'), (219, 'Library'), (223, 'Validator'), (224, 'Scorer')], verbose_name='file type'),
        ),
    ]
