# Generated by Django 3.1.2 on 2025-02-02 20:57

import common.ir18n.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_auto_20240502_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemextrainfo',
            name='run_twice',
            field=models.BooleanField(default=False, verbose_name='Run solutions twice'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='full_name',
            field=common.ir18n.fields.IR18nCharField(blank=True, max_length=200, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_name',
            field=common.ir18n.fields.IR18nCharField(blank=True, max_length=32, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='problemrelatedsourcefile',
            name='file_type',
            field=models.IntegerField(choices=[(215, "Author's solution"), (216, 'Checker'), (217, 'Contestant solution'), (218, 'Generator'), (219, 'Library'), (223, 'Validator'), (224, 'Scorer'), (225, 'Interactor')], verbose_name='file type'),
        ),
    ]
