# Generated by Django 3.1.2 on 2026-08-22 13:57

import common.ir18n.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_contest_scoring_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=common.ir18n.fields.IR18nCharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='scoring_policy',
            field=models.IntegerField(choices=[(0, 'Auto'), (1, 'Take last solution'), (2, 'Take best solution')], default=0, verbose_name='score policy'),
        ),
    ]
