# Generated by Django 3.1.2 on 2026-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200922_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolder',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
